Repository cosmos/gaia, pull requests merged in 2019-05, with the labels that each got.

#3 pass in binary names to version through build tags
  Makefile
  cmd/gaiacli/main.go
  contrib/devtools/Makefile
  contrib/gitian-descriptors/gitian-darwin.yml
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-windows.yml
  go.mod
  go.sum
Labels: ready-for-review

#8 Add Github Templates
  .github/CODEOWNERS
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: ready-for-review

#9 Update to support swagger
  .gitignore
  Makefile
  cmd/gaiacli/main.go
  cmd/gaiacli/statik/init.go
  cmd/gaiacli/swagger-ui/favicon-16x16.png
  cmd/gaiacli/swagger-ui/favicon-32x32.png
  cmd/gaiacli/swagger-ui/index.html
  cmd/gaiacli/swagger-ui/oauth2-redirect.html
  cmd/gaiacli/swagger-ui/swagger-ui-bundle.js
  cmd/gaiacli/swagger-ui/swagger-ui-bundle.js.map
  cmd/gaiacli/swagger-ui/swagger-ui-standalone-preset.js
  cmd/gaiacli/swagger-ui/swagger-ui-standalone-preset.js.map
  cmd/gaiacli/swagger-ui/swagger-ui.css
  cmd/gaiacli/swagger-ui/swagger-ui.css.map
  cmd/gaiacli/swagger-ui/swagger-ui.js
  cmd/gaiacli/swagger-ui/swagger-ui.js.map
  cmd/gaiacli/swagger-ui/swagger.yaml
Labels: REST, ready-for-review

#11 Fix lcd test
  go.mod
  go.sum
  lcd_test/helpers_test.go
Labels: ready-for-review

#5 Marko/Gaia Documentation Fixes
  CONTRIBUTING.md
  docs/DOCS_README.md
  docs/README.md
  docs/deploy-testnet.md
  docs/gaiacli.md
  docs/genesis.md
  docs/installation.md
  docs/join-testnet.md
  docs/keys.md
  docs/upgrade-node.md
  docs/validators/overview.md
Labels: docs, ready-for-review

#10 R4R: Updates for upstream PR (community pool spend proposal)
  .pending/features/gaiad/Update-Gaia-for-comm
  app/app.go
  app/sim_test.go
  cli_test/cli_test.go
  cli_test/test_helpers.go
  cmd/gaiacli/main.go
  go.mod
  go.sum
  lcd_test/helpers_test.go
  lcd_test/lcd_test.go
Labels: enhancement, ready-for-review

#16 Fix build workflow
  docs/DOCS_README.md
Labels: docs, ready-for-review

#21 Add docs translation
  docs/translations/cn/README.md
  docs/translations/cn/delegator-guide-cli.md
  docs/translations/cn/deploy-testnet.md
  docs/translations/cn/gaiacli.md
  docs/translations/cn/genesis-state.md
  docs/translations/cn/genesis.md
  docs/translations/cn/installation.md
  docs/translations/cn/join-mainnet.md
  docs/translations/cn/join-testnet.md
  docs/translations/cn/keys.md
  docs/translations/cn/launch/blog-1-cn.md
  docs/translations/cn/launch/blog-2-cn.md
  docs/translations/cn/ledger.md
  docs/translations/cn/validators/overview.md
  docs/translations/cn/validators/security.md
  docs/translations/cn/validators/validator-faq.md
  docs/translations/cn/validators/validator-setup.md
  docs/translations/cn/what-is-gaia.md
  docs/translations/kr/README.md
  docs/translations/kr/delegator-guide-cli.md
  docs/translations/kr/deploy-testnet.md
  docs/translations/kr/gaiacli.md
  docs/translations/kr/genesis.md
  docs/translations/kr/installation.md
  docs/translations/kr/join-testnet.md
  docs/translations/kr/keys.md
  docs/translations/kr/ledger.md
  docs/translations/kr/validators/overview.md
  docs/translations/kr/validators/security.md
  docs/translations/kr/validators/validator-faq.md
  docs/translations/kr/validators/validator-setup.md
  docs/translations/kr/what-is-gaia.md
Labels: docs, ready-for-review

#25 Remove Swagger
  .gitattributes
  Makefile
  cmd/gaiacli/main.go
  cmd/gaiacli/statik/init.go
  cmd/gaiacli/swagger-ui/favicon-16x16.png
  cmd/gaiacli/swagger-ui/favicon-32x32.png
  cmd/gaiacli/swagger-ui/index.html
  cmd/gaiacli/swagger-ui/oauth2-redirect.html
  cmd/gaiacli/swagger-ui/swagger-ui-bundle.js
  cmd/gaiacli/swagger-ui/swagger-ui-bundle.js.map
  cmd/gaiacli/swagger-ui/swagger-ui-standalone-preset.js
  cmd/gaiacli/swagger-ui/swagger-ui-standalone-preset.js.map
  cmd/gaiacli/swagger-ui/swagger-ui.css
  cmd/gaiacli/swagger-ui/swagger-ui.css.map
  cmd/gaiacli/swagger-ui/swagger.yaml
  go.mod
  go.sum
Labels: REST, ready-for-review
