Repository cosmos/gaia, pull requests merged in 2019-08, with the labels that each got.

#86 Update SDK to version latest master
  app/app.go
  app/app_test.go
  app/export.go
  app/sim_test.go
  app/utils.go
  cli_test/cli_test.go
  cli_test/test_helpers.go
  cmd/gaiad/main.go
  cmd/gaiad/replay.go
  cmd/gaiad/testnet.go
  go.mod
  go.sum
  lcd_test/helpers.go
  lcd_test/helpers_test.go
  lcd_test/lcd_test.go
  sims.mk
Labels: R4R

#87 Update SDK to Latest Master
  app/app.go
  go.mod
  go.sum
Labels: R4R

#89 v1.0.0-rc2 Cherry Picks
  app/app.go
  app/app_test.go
  app/export.go
  app/sim_test.go
  app/utils.go
  cli_test/cli_test.go
  cli_test/test_helpers.go
  cmd/gaiad/main.go
  cmd/gaiad/replay.go
  cmd/gaiad/testnet.go
  go.mod
  go.sum
  lcd_test/helpers.go
  lcd_test/helpers_test.go
  lcd_test/lcd_test.go
  sims.mk
Labels: R4R

#90 Updates reflecting sdk v0.36.0-rc4
  app/app.go
  app/sim_test.go
  go.mod
  go.sum
  lcd_test/helpers.go
  lcd_test/helpers_test.go
Labels: R4R

#91 v1.0.0-rc3 🍒 Picks
  app/app.go
  app/sim_test.go
  go.mod
  go.sum
  lcd_test/helpers.go
  lcd_test/helpers_test.go
Labels: R4R

#93 localnet-start requires build-linux
  Makefile
Labels: R4R

#94 update Gaia to latest SDK master
  app/app.go
  app/sim_test.go
  go.mod
  go.sum
  lcd_test/lcd_test.go
  sims.mk
Labels: R4R

#98 Cleanup installation docs
  docs/installation.md
Labels: R4R, docs

#100 Update SDK version to v0.36.0
  .clog.yaml
  CHANGELOG.md
  app/sim_test.go
  app/utils.go
  cli_test/cli_test.go
  go.mod
  go.sum
  lcd_test/lcd_test.go
  sims.mk
Labels: R4R

#99 Update SDK version to latest master
  cli_test/cli_test.go
  cmd/gaiad/testnet.go
  go.mod
  go.sum
  lcd_test/helpers.go
  lcd_test/lcd_test.go
Labels: R4R

#101 v1.0.0 Changelog Updates
  .github/PULL_REQUEST_TEMPLATE.md
  .pending/breaking/gaiacli/3715-query-distr-rew
  .pending/breaking/gaiacli/40-rest-server-s---c
  .pending/breaking/gaiacli/4027-gaiad-and-gaiac
  .pending/breaking/gaiacli/4142-Turn-gaiacli-tx
  .pending/breaking/gaiacli/4228-merge-gaiakeyutil-into-gaiacli
  .pending/breaking/gaiad/3985-ValidatorPowerR
  .pending/breaking/gaiad/4027-gaiad-and-gaiac
  .pending/breaking/gaiad/4159-use-module-patt
  .pending/breaking/gaiad/4272-Merge-gaiarepla
  .pending/breaking/rest/3715-Update-distribu
  .pending/breaking/rest/3942-Support-query-t
  .pending/breaking/rest/4049-update-tag
  .pending/breaking/rest/The-auth-accounts-ad
  .pending/bugfixes/gaiacli/3945-There-s-no-chec
  .pending/bugfixes/gaiacli/4190-Fix-redelegatio
  .pending/bugfixes/gaiacli/4219-Empty-mnemonic-
  .pending/bugfixes/gaiacli/4345-Improved-NanoX-detection
  .pending/bugfixes/gaiad/4113-Fix-incorrect-G
  .pending/features/gaiad/Add-migrate-command-
  .pending/features/gaiad/Update-Gaia-for-comm
  .pending/improvements/gaiacli/3426-remove-redundant-account-check
  .pending/improvements/gaiacli/4227-Support-for-Ledger-App-1.5
  .pending/improvements/gaiad/4042-Add-description
  .pending/improvements/gaiad/4062-Remove-cmd-gaia
  .pending/improvements/gaiad/4064-Remove-dep-and-
  .pending/improvements/gaiad/4080-add-missing-inv
  .pending/improvements/gaiad/4343-Upgrade-toolcha
  .pending/improvements/rest/2007-Return-200-status-code-on-empty-results
  .pending/improvements/rest/4123-Fix-typo-url-er
  .pending/improvements/rest/4129-Translate-doc-c
  .pending/improvements/rest/4141-Fix-txs-encode-
  CHANGELOG.md
  CONTRIBUTING.md
  contrib/devtools/Makefile
Labels: R4R

#102 Remove clog config
  .clog.yaml
  CHANGELOG.md
  CONTRIBUTING.md
Labels: R4R, docs

#105 fix black listed addrs bug in bank
  app/app.go
  app/app_test.go
Labels: R4R, state-machine-breaking

#108 v2.0.0-rc1 Cherry Picks
  .clog.yaml
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
  CONTRIBUTING.md
  app/app.go
  app/app_test.go
  contrib/devtools/Makefile
  go.mod
  go.sum
Labels: R4R

#107 Build with Go 1.12.9
  contrib/gitian-build.sh
  contrib/gitian-descriptors/gitian-darwin.yml
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-windows.yml
Labels: R4R

#109 v.37.0 rc2
  CHANGELOG.md
  go.mod
  go.sum
Labels: R4R

#110 Update CHANGELOG - v2.0.0
  CHANGELOG.md
Labels: R4R
