Repository cosmos/gaia, pull requests merged in 2019-06, with the labels that each got.

#36 Add disclaimer section to README
  README.md
Labels: docs, ready-for-review

#37 Revert removal of auth/bank commands from root
  .pending/breaking/gaiacli/Bank-and-Auth-module
  cli_test/test_helpers.go
  cmd/gaiacli/main.go
Labels: CLI, ready-for-review

#38 Updates to reflect SDK codec client changes
  cmd/gaiacli/main.go
  go.mod
  go.sum
  lcd_test/helpers_test.go
Labels: ready-for-review

#19 Contract test [GET]
  .circleci/config.yml
  .gitignore
  Makefile
  cmd/contract_tests/main.go
  contrib/get_node.sh
  dredd.yml
  go.mod
  go.sum
  lcd_test/helpers.go
  lcd_test/helpers_test.go
  lcd_test/lcd_test.go
  lcd_test/testdata/setup.sh
  lcd_test/testdata/state.tar.gz
Labels: REST, ready-for-review

#40 Update to SDK's latest master
  .pending/breaking/gaiacli/40-rest-server-s---c
  app/params.go
  app/sim_test.go
  go.mod
  go.sum
Labels: ready-for-review

#41 R4R Staking ValidatorPowerRank to use "Potential Consensus Power"
  .pending/breaking/gaiad/3985-ValidatorPowerR
  cli_test/cli_test.go
  cli_test/test_helpers.go
  cmd/gaiad/testnet.go
  go.mod
  lcd_test/helpers.go
  lcd_test/lcd_test.go
Labels: ready-for-review

#46 Upgrade to latest SDK version (73700df8c)
  .pending/breaking/rest/The-auth-accounts-ad
  app/sim_test.go
  cmd/gaiacli/main.go
  go.mod
  go.sum
  lcd_test/helpers.go
  lcd_test/helpers_test.go
Labels: ready-for-review

#55 Fix reproducible builds docs
  docs/reproducible-builds.md
Labels: build, ready-for-review

#53 Update latest SDK version: Events Refactor
  .circleci/config.yml
  app/app.go
  app/export.go
  cli_test/cli_test.go
  cmd/gaiad/replay.go
  cmd/gaiad/testnet.go
  contrib/devtools/Makefile
  go.mod
  go.sum
  lcd_test/lcd_test.go
Labels: ready-for-review
