Repository cosmos/gaia, pull requests merged in 2019-12, with the labels that each got.

#205 Update Migration Doc with Proposal Values
  docs/migration/cosmoshub-2.md
Labels: R4R, docs

#207 Bump SDK Commit
  app/app.go
  cli_test/cli_test.go
  go.mod
  go.sum
Labels: R4R

#209 Updated PR template, stale and codecov settings
  .codecov.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/staly.yml
  CONTRIBUTING.md
Labels: R4R

#204 deprecate GOPATH references on docs
  docs/deploy-testnet.md
  docs/installation.md
  docs/join-testnet.md
  docs/translations/cn/deploy-testnet.md
  docs/translations/cn/installation.md
  docs/translations/cn/join-testnet.md
  docs/translations/kr/deploy-testnet.md
  docs/translations/kr/installation.md
  docs/translations/kr/join-testnet.md
  docs/translations/kr/upgrade-node.md
  docs/upgrade-node.md
Labels: docs

#210 update Gaia with to latest SDK master
  app/app.go
  app/sim_test.go
  app/utils.go
  go.mod
  go.sum
Labels: R4R

#211 Update against sdk's keys commands changes
  go.mod
  go.sum
Labels: CLI, R4R

#208 Ledger + Lunie guide
  README.md
  docs/images/cosmos-hub-image.jpg
  docs/ledger-tuto-dev-mode.png
  docs/ledger-tuto-lunie-address.png
  docs/ledger-tuto-lunie-option.png
  docs/ledger-tuto-manager.png
  docs/ledger-tuto-search.png
  docs/ledger.md
Labels: R4R, docs

#213 Update cosmoshub-2.md
  docs/migration/cosmoshub-2.md
Labels: R4R, docs

#218 rename staly.yml -> stale.yml
  .github/stale.yml
Labels: R4R

#212 Bump SDK master version
  CHANGELOG.md
  Makefile
  cli_test/cli_test.go
  cli_test/test_helpers.go
  cmd/gaiad/genaccounts.go
  cmd/gaiad/testnet.go
  go.mod
  go.sum
  lcd_test/helpers.go
  lcd_test/helpers_test.go
  lcd_test/lcd_test.go
Labels: CLI, R4R

#221 Hide unnecessarily exported function to better coverage report
  app/sim_test.go
  app/utils.go
Labels: R4R

#215 Update simulation tests
  app/app.go
  app/app_test.go
  app/sim_bench_test.go
  app/sim_test.go
  app/utils.go
  go.mod
  go.sum
Labels: R4R

#239 Bump SDK commit to the latest master
  app/app.go
  app/sim_bench_test.go
  cli_test/cli_test.go
  cli_test/test_helpers.go
  cmd/gaiacli/main.go
  cmd/gaiad/main.go
  cmd/gaiad/testnet.go
  go.mod
  go.sum
  lcd_test/helpers.go
  lcd_test/helpers_test.go
  lcd_test/lcd_test.go
Labels: R4R
