Repository cosmos/gaia, pull requests merged in 2019-07, with the labels that each got.

#65 Various updates to tools
  .circleci/config.yml
  Makefile
  contrib/devtools/Makefile
Labels: build, ready-for-review

#56 Update to latest SDK: Supply
  Makefile
  app/app.go
  app/app_test.go
  app/genesis.go
  app/sim_test.go
  app/utils.go
  cli_test/README.md
  cli_test/cli_test.go
  cli_test/test_helpers.go
  cmd/gaiacli/main.go
  cmd/gaiad/main.go
  cmd/gaiad/testnet.go
  docs/delegator-guide-cli.md
  docs/gaiacli.md
  docs/genesis-state.md
  docs/genesis.md
  docs/translations/cn/delegator-guide-cli.md
  docs/translations/cn/gaiacli.md
  docs/translations/cn/genesis-state.md
  docs/translations/cn/genesis.md
  docs/translations/kr/delegator-guide-cli.md
  docs/translations/kr/gaiacli.md
  go.mod
  go.sum
  lcd_test/helpers.go
  lcd_test/helpers_test.go
  lcd_test/lcd_test.go
Labels: ready-for-review

#60 Add migrate command to gaiad
  .pending/features/gaiad/Add-migrate-command-
  cmd/gaiad/main.go
  go.mod
  go.sum
Labels: CLI, R4R

#66 Remove statik from contrib/devtools/Makefile
  contrib/devtools/Makefile
  docs/installation.md
  docs/translations/cn/installation.md
  docs/translations/kr/installation.md
  go.sum
Labels: R4R, build

#77 Update SDK version
  app/app.go
  app/sim_test.go
  cli_test/test_helpers.go
  go.mod
  go.sum
Labels: R4R

#80 Update deterministic build system to build with Go 1.12.7
  contrib/gitian-build.sh
  contrib/gitian-descriptors/gitian-darwin.yml
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-windows.yml
Labels: R4R
