Repository cosmos/gaia, pull requests merged in 2019-11, with the labels that each got.

#175 Bump SDK to latest master
  app/params.go
  app/sim_test.go
  cli_test/cli_test.go
  go.mod
  go.sum
Labels: R4R

#181 v2.0.3-rc1
  CHANGELOG.md
  app/sim_test.go
  go.mod
  go.sum
Labels: R4R

#182 changelog: add v2.0.3 section
  CHANGELOG.md
Labels: R4R

#190 Bump SDK version to latest master
  CHANGELOG.md
  app/app.go
  go.mod
  go.sum
Labels: R4R

#185 Migration Instructions/Doc: cosmoshub-2
  docs/migration/README.md
  docs/migration/cosmoshub-2.md
Labels: R4R

#188 Add some linting to gaia
  .golangci.yml
  app/app.go
  app/app_test.go
  app/benchmarks/txsize_test.go
  app/export.go
  app/sim_test.go
  cli_test/test_helpers.go
  cmd/contract_tests/main.go
  cmd/gaiad/replay.go
  cmd/gaiad/testnet.go
  cmd/gaiadebug/hack.go
  cmd/gaiadebug/main.go
  lcd_test/helpers.go
  lcd_test/helpers_test.go
  lcd_test/lcd_test.go
Labels: R4R, code-hygiene

#164 Drop on-disk keybase in favor of keyring
  Makefile
  cli_test/cli_test.go
  cli_test/test_helpers.go
  cmd/gaiacli/main.go
  cmd/gaiad/genaccounts.go
  cmd/gaiad/main.go
  cmd/gaiad/testnet.go
  docs/delegator-guide-cli.md
  docs/gaiacli.md
  go.mod
  go.sum
  lcd_test/helpers.go
  lcd_test/helpers_test.go
  lcd_test/lcd_test.go
Labels: R4R

#191 Remove gaiadebug
  CHANGELOG.md
  cmd/gaiacli/main.go
  cmd/gaiad/main.go
  cmd/gaiadebug/README.md
  cmd/gaiadebug/hack.go
  cmd/gaiadebug/main.go
Labels: CLI

#194 [DOCS][KR] Update Gaia Docs KR translation
  docs/gaiacli.md
  docs/genesis.md
  docs/hd-wallets.md
  docs/join-mainnet.md
  docs/ledger.md
  docs/translations/kr/deploy-testnet.md
  docs/translations/kr/gaiacli.md
  docs/translations/kr/genesis-state.md
  docs/translations/kr/genesis.md
  docs/translations/kr/hd-wallets.md
  docs/translations/kr/installation.md
  docs/translations/kr/join-mainnet.md
  docs/translations/kr/ledger.md
  docs/translations/kr/upgrade-node.md
  docs/translations/kr/validators/security.md
Labels: R4R, docs

#196 Upgrade module
  CHANGELOG.md
  app/app.go
  docs/live-upgrade-tutorial.md
  go.mod
  go.sum
Labels: R4R
