Repository cosmos/gaia, pull requests merged in 2020-02, with the labels that each got.

#276 Update bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.md
Labels: R4R

#281 Bump SDK commit
  app/app.go
  cli_test/cli_test.go
  cli_test/test_helpers.go
  cmd/gaiad/genaccounts.go
  cmd/gaiad/main.go
  cmd/gaiad/testnet.go
  go.mod
  go.sum
  lcd_test/helpers.go
  lcd_test/helpers_test.go
  lcd_test/lcd_test.go
Labels: R4R

#282 Bump SDK master commit
  .circleci/config.yml
  app/app.go
  app/codec.go
  contrib/localnet-blocks-test.sh
  go.mod
  go.sum
  lcd_test/lcd_test.go
Labels: R4R

#283 v2.0.6 RC1
  CHANGELOG.md
  go.mod
  go.sum
Labels: R4R

#284 Add v2.0.6 changelog entry
  CHANGELOG.md
Labels: R4R

#279 docs: add pruning section
  README.md
  docs/gaia-tutorials/join-mainnet.md
Labels: docs

#285 update: gaia to master of the sdk
  Makefile
  app/app.go
  app/benchmarks/txsize_test.go
  app/codec.go
  app/codec/codec.go
  app/codec/codec.pb.go
  app/codec/codec.proto
  app/export.go
  app/genesis.go
  app/sim_test.go
  buf.yaml
  cli_test/cli_test.go
  cli_test/test_helpers.go
  cmd/gaiacli/main.go
  cmd/gaiad/genaccounts.go
  cmd/gaiad/main.go
  cmd/gaiad/testnet.go
  contrib/devtools/Makefile
  go.mod
  go.sum
  lcd_test/helpers.go
  lcd_test/lcd_test.go
  scripts/protocgen.sh
  third_party/proto/cosmos-proto/cosmos.proto
  third_party/proto/cosmos-sdk/types/types.proto
  third_party/proto/cosmos-sdk/x/auth/types/types.proto
  third_party/proto/cosmos-sdk/x/auth/vesting/types/types.proto
  third_party/proto/cosmos-sdk/x/supply/types/types.proto
  third_party/proto/gogoproto/gogo.proto
Labels: R4R, dependencies

#295 ci: add proto checks to ci
  .circleci/config.yml
Labels: R4R

#298 Bump SDK master commit
  Makefile
  app/app.go
  app/codec/codec.go
  app/codec/codec.pb.go
  app/codec/codec.proto
  app/codec/msgs.go
  cmd/gaiad/testnet.go
  go.mod
  go.sum
  third_party/proto/cosmos-sdk/types/types.proto
  third_party/proto/cosmos-sdk/x/auth/types/types.proto
  third_party/proto/cosmos-sdk/x/evidence/types/types.proto
  third_party/proto/cosmos-sdk/x/supply/types/types.proto
Labels: R4R
