Repository cosmos/gaia, pull requests merged in 2020-05, with the labels that each got.

#390 bump sdk version
  CHANGELOG.md
  go.mod
  go.sum
Labels: R4R

#392 bump change log
  CHANGELOG.md
Labels: R4R, automerge

#394 Add validate-signatures cmd
  cli_test/cli_test.go
  cli_test/test_helpers.go
  cmd/gaiacli/main.go
Labels: R4R

#393 Update join-mainnet.md
  docs/gaia-tutorials/join-mainnet.md
Labels: R4R, automerge, docs

#391 bump sdk commit
  app/app.go
  cli_test/cli_test.go
  cli_test/test_helpers.go
  cmd/gaiacli/main.go
  cmd/gaiad/main.go
  go.mod
  go.sum
  lcd_test/helpers.go
Labels: R4R

#383 Readme.md improvements
  README.md
Labels: R4R, automerge, docs

#399 Use uncached context in Gaia InitializeAndSeal() call
  app/app.go
Labels: IBC, R4R, bug

#384 Makefile: pass build directory to go build -o flag
  Makefile
Labels: R4R

#396 add Jonathan to CODEOWNERS
  .github/CODEOWNERS
Labels: R4R, automerge

#371 Updated docs website
  docs/.vuepress/config.js
  docs/package-lock.json
  docs/package.json
Labels: automerge, docs

#408 docker: add user
  Dockerfile
Labels: automerge

#407 add git pre-commit hook
  CONTRIBUTING.md
  contrib/githooks/README.md
  contrib/githooks/pre-commit
Labels: R4R

#355 ci: new step to check build sanity vs cosmos-sdk master
  .github/workflows/build-latest-sdk.yml
Labels: R4R

#397 Update README.md to reflect latest release and let users know where to find releases
  README.md
Labels: R4R, automerge

#410 minor code cleanup
  .github/workflows/lint.yml
  cmd/gaiacli/main.go
  cmd/gaiad/main.go
  cmd/gaiad/testnet.go
Labels: R4R, automerge
