Repository cosmos/gaia, pull requests merged in 2020-03, with the labels that each got.

#308 Bump SDK master commit
  Makefile
  app/app.go
  app/app_test.go
  app/benchmarks/txsize_test.go
  app/codec/codec.go
  app/codec/codec.pb.go
  app/codec/codec.proto
  app/codec/msgs.go
  app/genesis.go
  app/sim_bench_test.go
  app/sim_test.go
  cli_test/cli_test.go
  cmd/gaiacli/main.go
  cmd/gaiad/genaccounts.go
  cmd/gaiad/main.go
  cmd/gaiad/replay.go
  go.mod
  go.sum
  lcd_test/helpers.go
  lcd_test/lcd_test.go
Labels: R4R

#316 Build with Go 1.14
  .circleci/config.yml
  README.md
  contrib/gitian-build.sh
  contrib/gitian-descriptors/gitian-darwin.yml
  contrib/gitian-descriptors/gitian-linux.yml
  contrib/gitian-descriptors/gitian-multi.yml
  contrib/gitian-descriptors/gitian-windows.yml
  docs/gaia-tutorials/installation.md
  go.mod
  go.sum
Labels: R4R

#315 v2.0.7-RC1
  CHANGELOG.md
  go.mod
  go.sum
Labels: R4R

#319 Set v2.0.7 Changelog
  CHANGELOG.md
Labels: R4R

#312 proto: remove proto mentions
  .circleci/config.yml
  Makefile
  scripts/protocgen.sh
  third_party/proto/cosmos-proto/cosmos.proto
  third_party/proto/cosmos-sdk/types/types.proto
  third_party/proto/cosmos-sdk/x/auth/types/types.proto
  third_party/proto/cosmos-sdk/x/auth/vesting/types/types.proto
  third_party/proto/cosmos-sdk/x/evidence/types/types.proto
  third_party/proto/cosmos-sdk/x/supply/types/types.proto
  third_party/proto/gogoproto/gogo.proto
Labels: code-hygiene

#323 Update cosmos sdk to last master branch
  cli_test/cli_test.go
  go.mod
  go.sum
  lcd_test/lcd_test.go
Labels: R4R

#333 docs: link checker
  .github/workflows/linkchecker.yml
Labels: docs

#334 Bump SDK version
  go.mod
  go.sum
  lcd_test/helpers.go
Labels: R4R

#289 test github actions
  .circleci/config.yml
  .github/workflows/sims.yml
  .github/workflows/test.yml
Labels: build
