Repository cosmos/gaia, pull requests merged in 2020-01, with the labels that each got.

#247 Update SDK Commit & Update CLI Doc
  app/app.go
  app/app_test.go
  app/export.go
  app/sim_bench_test.go
  app/sim_test.go
  cli_test/cli_test.go
  cli_test/test_helpers.go
  cmd/gaiad/main.go
  cmd/gaiad/replay.go
  docs/resources/gaiacli.md
  docs/translations/cn/gaiacli.md
  docs/translations/kr/gaiacli.md
  go.mod
  go.sum
  lcd_test/helpers.go
  lcd_test/helpers_test.go
Labels: R4R

#251 v2.0.4-RC1
  .circleci/config.yml
  CHANGELOG.md
  cli_test/cli_test.go
  cli_test/test_helpers.go
  docs/gaiacli.md
  docs/translations/cn/gaiacli.md
  docs/translations/kr/gaiacli.md
  go.mod
  go.sum
  lcd_test/helpers_test.go
Labels: R4R

#252 v2.0.4 Changelog
  CHANGELOG.md
Labels: R4R

#253 Bump SDK master commit
  cli_test/cli_test.go
  cli_test/test_helpers.go
  go.mod
  go.sum
  lcd_test/lcd_test.go
Labels: R4R

#250 Docs-update
  .circleci/config.yml
  .github/workflows/linkchecker.yml
  .gitignore
  Makefile
  docs/.vuepress/components/home.vue
  docs/.vuepress/config.js
  docs/.vuepress/public/logo-bw.svg
  docs/.vuepress/public/logo.svg
  docs/.vuepress/styles/index.styl
  docs/DOCS_README.md
  docs/README.md
  docs/delegators/delegator-faq.md
  docs/delegators/delegator-guide-cli.md
  docs/delegators/delegator-security.md
  docs/gaia-tutorials/README.md
  docs/gaia-tutorials/deploy-testnet.md
  docs/gaia-tutorials/installation.md
  docs/gaia-tutorials/join-mainnet.md
  docs/gaia-tutorials/join-testnet.md
  docs/gaia-tutorials/upgrade-node.md
  docs/gaia-tutorials/what-is-gaia.md
  docs/hub-overview/README.md
  docs/hub-overview/overview.md
  docs/images/README.md
  docs/launch/README.md
  docs/migration/README.md
  docs/package-lock.json
  docs/package.json
  docs/resources/README.md
  docs/resources/archives.md
  docs/resources/gaiacli.md
  docs/resources/genesis.md
  docs/resources/hd-wallets.md
  docs/resources/ledger.md
  docs/resources/reproducible-builds.md
  docs/resources/service-providers.md
  docs/translations/README.md
  docs/translations/readme.md
  docs/validators/README.md
  docs/validators/kms/kms.md
  docs/validators/kms/kms_ledger.md
  docs/validators/overview.md
  docs/validators/security.md
  docs/validators/validator-faq.md
  docs/validators/validator-setup.md
  docs/versions
  networks/README.md
Labels: R4R, docs

#264 v2.0.5 rc1
  CHANGELOG.md
  go.mod
  go.sum
Labels: R4R

#265 add v2.0.5 changes to CHANGELOG
  CHANGELOG.md
Labels: R4R

#267 Exec go mod tidy
  go.sum
Labels: R4R

#259 Bump SDK master commit
  app/app.go
  cmd/gaiad/genaccounts.go
  cmd/gaiad/replay.go
  cmd/gaiad/testnet.go
  go.mod
  go.sum
  lcd_test/helpers.go
  lcd_test/lcd_test.go
Labels: R4R, blocked, dependencies

#271 Build against cosmos-sdk 0.38.0
  cmd/gaiacli/main.go
  cmd/gaiad/genaccounts.go
  cmd/gaiad/main.go
  cmd/gaiad/testnet.go
  go.mod
  go.sum
  lcd_test/lcd_test.go
Labels: R4R

#272 build against latest master
  go.mod
  go.sum
  lcd_test/helpers_test.go
Labels: R4R
