Repository cosmos/gaia, pull requests merged in 2020-04, with the labels that each got.

#346 Bump SDK Master Rev
  cli_test/test_helpers.go
  cmd/gaiad/genaccounts.go
  cmd/gaiad/testnet.go
  go.mod
  go.sum
  lcd_test/helpers.go
  lcd_test/helpers_test.go
  lcd_test/lcd_test.go
Labels: R4R

#347 add validate cmd to tx and query subcmds
  cmd/gaiacli/main.go
Labels: CLI, R4R

#350 v2.0.8 RC1
  CHANGELOG.md
  go.mod
  go.sum
Labels: R4R

#351 v2.0.8 Changelog
  CHANGELOG.md
Labels: R4R

#349 Refresh against cosmos-sdk's latest master
  app/app.go
  app/benchmarks/txsize_test.go
  cli_test/cli_test.go
  cmd/gaiacli/main.go
  cmd/gaiad/genaccounts.go
  cmd/gaiad/main.go
  cmd/gaiad/testnet.go
  go.mod
  go.sum
  lcd_test/helpers.go
  lcd_test/helpers_test.go
  lcd_test/lcd_test.go
Labels: R4R

#326 try changes with offline flag
  CHANGELOG.md
  cli_test/cli_test.go
  cli_test/test_helpers.go
Labels: R4R

#305 Update docs website
  docs/.vuepress/config.js
  docs/package-lock.json
  docs/package.json
Labels: R4R, docs

#357 ci: fix circleci docker jobs
  .circleci/config.yml
Labels: R4R

#362 Install linter and code coverage as github actions
  .circleci/config.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
Labels: R4R

#363 Makefile: strip debug symbols by default
  Makefile
Labels: R4R

#288 IBC Alpha Updates
  Makefile
  app/app.go
  app/app_test.go
  app/export.go
  app/sim_test.go
  cli_test/cli_test.go
  cli_test/test_helpers.go
  cmd/gaiad/genaccounts.go
  cmd/gaiad/main.go
  cmd/gaiad/replay.go
  cmd/gaiad/testnet.go
  contrib/Dockerfile.test
  contrib/single-node.sh
  go.mod
  go.sum
  lcd_test/helpers.go
  lcd_test/helpers_test.go
  lcd_test/lcd_test.go
Labels: WIP, pinned

#375 refresh againt cosmos-sdk master
  cli_test/cli_test.go
  cli_test/test_helpers.go
  go.mod
  go.sum
Labels: R4R

#382 install mergify
  .mergify.yml
Labels: R4R

#381 bump SDK commit
  app/app.go
  app/benchmarks/txsize_test.go
  app/genesis.go
  app/sim_test.go
  cli_test/cli_test.go
  cli_test/test_helpers.go
  cmd/gaiacli/main.go
  cmd/gaiad/genaccounts.go
  cmd/gaiad/main.go
  go.mod
  go.sum
  lcd_test/helpers.go
Labels: R4R, dependencies
