Repository cosmos/gaia, pull requests merged in 2021-04, with the labels that each got.

#807 Bump sdk and tendermint dependencies
  go.mod
  go.sum
Labels: automerge, backport/4.2.x

#809 minor doc update
  SECURITY.md
Labels: automerge, backport/4.2.x

#820 Bump Tendermint version to v0.34.10
  CHANGELOG.md
  go.mod
  go.sum
Labels: automerge

#827 Update README to cosmoshub-4
  README.md
  docs/resources/archives.md
Labels: docs

#826 Updates Service Provider Guide
  docs/gaia-tutorials/installation.md
  docs/gaia-tutorials/join-mainnet.md
  docs/resources/service-providers.md
Labels: docs
