Repository cosmos/gaia, pull requests merged in 2021-03, with the labels that each got.

#761 Add Security process
  SECURITY.md
Labels: automerge

#762 Lower limit for automerge
  .mergify.yml
Labels: automerge

#763 Update join-mainnet.md
  docs/gaia-tutorials/join-mainnet.md
Labels: automerge

#772 Remove v4.0.x branch backport rule
  .mergify.yml
Labels: automerge

#771 Bump Cosmos SDK to v0.42.2
  CHANGELOG.md
  go.mod
  go.sum
Labels: automerge, backport/4.1.x

#769 Add security process condition
  SECURITY.md
Labels: automerge, backport/4.1.x

#774 Adding `sim` label for PRs to run long-running non-determinism sim
  .github/workflows/sim-label.yml
Labels: automerge

#778 Adding `sim` label for PRs to run long-running non-determinism sim (#…
  .github/workflows/sim-label.yml
Labels: automerge

#781 removing deps that are no longer needed
  app/migrate.go
  app/prop29.go
  app/prop29_test.go
  go.mod
  go.sum
Labels: automerge, backport/4.1.x, sim

#783 changelog for v4.1.2 release
  CHANGELOG.md
Labels: automerge, backport/4.1.x

#786 Add some process around timed releases
  RELEASING.md
  SECURITY.md
Labels: automerge, backport/4.1.x

#791 Update backport label for v4.2.x
  .mergify.yml
Labels: automerge
