Repository cosmos/gaia, pull requests merged in 2021-11, with the labels that each got.

#979 gaia v6.0.0-rc2
  .github/workflows/lint.yml
  CHANGELOG.md
  app/app.go
  app/migrate.go
  app/pubkey_replacement.go
  cmd/gaiad/cmd/root.go
  cmd/gaiad/cmd/testnet.go
  go.mod
  go.sum
Labels: R4R

#1051 Re-enable parameter index in gov docs
  docs/.vuepress/config.js
Labels: docs

#1077 Vega 6.0.0
  app/app.go
Labels: WIP
