Repository cosmos/gaia, pull requests merged in 2023-01, with the labels that each got.

#2022 chore: Update changelog for rc2
  CHANGELOG.md
Labels: A:backport/v8.0.x

#2028 Fix: Bump pfm
  app/keepers/keepers.go
  go.mod
  go.sum
Labels: A:backport/v8.0.x

#2030 refactor: pass routerKeeper to appKeeper as a pointer
  app/keepers/keepers.go
Labels: A:backport/v8.0.x

#2036 chore: update changelog for rc3
  CHANGELOG.md
Labels: A:backport/v8.0.x

#2047 chore: add v9 changelog
  CHANGELOG.md
Labels: A:backport/v9.0.x

#2054 chore: bump ibc ics and pfm for ibc v4
  ante/ante.go
  app/app.go
  app/app_helpers.go
  app/keepers/keepers.go
  app/keepers/keys.go
  app/modules.go
  app/upgrades/v7/constants.go
  app/upgrades/v7/upgrades.go
  app/upgrades/v8/upgrades.go
  cmd/gaiad/cmd/testnet.go
  go.mod
  go.sum
  tests/e2e/e2e_setup_test.go
  tests/e2e/genesis.go
  x/globalfee/ante/antetest/fee_test.go
Labels: A:backport/v9.0.x

#2045 Update testnet tutorial for v8-Rho upgrade
  docs/hub-tutorials/join-testnet.md
Labels: A:backport/v8.0.x, A:backport/v9.0.x

#2058 chore: update changelog for v9-rc1
  CHANGELOG.md
Labels: A:backport/v9.0.x

#2069 chore: update final v8 changelog
  CHANGELOG.md
Labels: A:backport/v8.0.x, A:backport/v9.0.x

#2080 Reintroduce missing code for rest endpoint wiring
  app/app.go
  tests/e2e/e2e_rest_regression_test.go
  tests/e2e/e2e_test.go
  tests/e2e/http_util.go
Labels: A:backport/v8.0.x, A:backport/v9.0.x

#2093 chore: Update changelog for v8-rc4
  CHANGELOG.md
Labels: release: Rho, A:backport/v8.0.x, A:backport/v9.0.x

#2095 feat: Add go version check
  Makefile
Labels: A:backport/v8.0.x, A:backport/v9.0.x

#2104 chore: Update changelog for v8-rc5
  CHANGELOG.md
Labels: release: Rho, A:backport/v8.0.x, A:backport/v9.0.x

#2108 chore: Update changelog for v8 final release
  CHANGELOG.md
Labels: A:backport/v8.0.x, A:backport/v9.0.x

#2068 chore: Update Gaia roadmap
  docs/roadmap/cosmos-hub-roadmap-2.0.md
Labels: A:backport/v8.0.x, A:backport/v9.0.x

#2114 chore: Update v8 release date on changelog
  CHANGELOG.md
Labels: A:backport/v8.0.x, A:backport/v9.0.x

#2091 docs: bypass messages
  ante/ante.go
  docs/modules/globalfee.md
  x/globalfee/ante/fee.go
Labels: A:backport/v8.0.x, A:backport/v9.0.x

#2124 chore: Fix roadmap
  docs/roadmap/cosmos-hub-roadmap-2.0.md
Labels: A:backport/v8.0.x, A:backport/v9.0.x
