Repository cosmos/gaia, pull requests merged in 2023-07, with the labels that each got.

#2627 feat: add query local min-gas-price
  .changelog/unreleased/features/2629-add-query-local-min-gas-prices.md
  app/app.go
  tests/e2e/e2e_rest_regression_test.go
Labels: A:backport/v10.0.x

#2587 feat: refactor base E2E tests
  Dockerfile
  e2e.Dockerfile
  go.mod
  go.sum
  tests/e2e/address.go
  tests/e2e/chain.go
  tests/e2e/docker/hermes.Dockerfile
  tests/e2e/e2e_bank_test.go
  tests/e2e/e2e_distribution_test.go
  tests/e2e/e2e_encode_test.go
  tests/e2e/e2e_evidence_test.go
  tests/e2e/e2e_exec_test.go
  tests/e2e/e2e_feegrant_test.go
  tests/e2e/e2e_gov_test.go
  tests/e2e/e2e_ibc_test.go
  tests/e2e/e2e_rest_regression_test.go
  tests/e2e/e2e_setup_test.go
  tests/e2e/e2e_slashing_test.go
  tests/e2e/e2e_staking_test.go
  tests/e2e/e2e_test.go
  tests/e2e/e2e_vesting_test.go
  tests/e2e/genesis.go
  tests/e2e/http_util.go
  tests/e2e/io.go
  tests/e2e/keys.go
  tests/e2e/query.go
  tests/e2e/scripts/hermes_bootstrap.sh
  tests/e2e/util.go
  tests/e2e/validator.go
  tests/ics/interchain_security_test.go
Labels: tests

#2644 fix: use the latest release of hermes for e2e
  tests/e2e/docker/hermes.Dockerfile
Labels: build

#2671 fix: add "v" prefix to release binary version
  .goreleaser.yml
Labels: A:backport/v11.x
