Repository cosmos/gaia, pull requests merged in 2023-11, with the labels that each got.

#2782 docs: fix "follwing" typo
  docs/resources/genesis.md
Labels: A:backport/v12.x, A:backport/v13.x

#2792 docs: add changelog entry for ledger fix
  .changelog/unreleased/bug-fixes/2763-ledger-fix.md
Labels: A:backport/v13.x

#2809 (deps!): bump ICS to v2.3.0-provider-lsm (#2808)
  .changelog/unreleased/api-breaking/2781-bump-ics.md
  .changelog/unreleased/api-breaking/2809-bump-ics.md
  .changelog/unreleased/dependencies/2781-bump-ics.md
  .changelog/unreleased/dependencies/2809-bump-ics.md
  .changelog/unreleased/features/2781-bump-ics.md
  .changelog/unreleased/features/2809-bump-ics.md
  .changelog/unreleased/state-breaking/2781-bump-ics.md
  .changelog/unreleased/state-breaking/2809-bump-ics.md
  go.mod
  go.sum
Labels: A:backport/v14.x

#2811 deps!: bump ics to `v2.3.0-provider-lsm-rc0`
  go.mod
  go.sum
Labels: A:backport/v14.x

#2825 deps!: bump ICS to v2.4.0-lsm
  .changelog/unreleased/api-breaking/2825-bump-ics.md
  .changelog/unreleased/dependencies/2825-bump-ics.md
  .changelog/unreleased/features/2821-evidence-height.md
  .changelog/unreleased/features/2825-bump-ics.md
  .changelog/unreleased/state-breaking/2825-bump-ics.md
  CHANGELOG.md
  go.mod
  go.sum
Labels: A:backport/v14.1.x

#2827 docs: deprecate v14.0.0 changelog section
  .changelog/v14.0.0/summary.md
Labels: A:backport/v14.1.x
