Repository cosmos/gaia, pull requests merged in 2023-08, with the labels that each got.

#2603 docs: global fee adr
  docs/architecture/README.md
  docs/architecture/adr-002-globalfee.md
Labels: A:backport/v11.x

#2675 fix: Fix pointer to store upgrades inside loop
  app/app.go
Labels: A:backport/v11.0.x

#2643 deps!: use cosmos-sdk v0.45.16-lsm-ics
  .changelog/unreleased/api-breaking/2643-lsm.md
  .changelog/unreleased/dependencies/2643-bump-ics.md
  .changelog/unreleased/dependencies/2643-bump-sdk.md
  .changelog/unreleased/features/2643-lsm.md
  .changelog/unreleased/state-breaking/2643-lsm.md
  app/helpers/test_helpers.go
  app/upgrades/v12/constants.go
  app/upgrades/v12/upgrades.go
  cmd/gaiad/cmd/testnet.go
  contrib/scripts/local-gaia.sh
  docs/delegators/delegator-faq.md
  docs/validators/validator-faq.md
  docs/validators/validator-setup.md
  go.mod
  go.sum
  tests/e2e/e2e_exec_test.go
  tests/e2e/e2e_ibc_test.go
  tests/e2e/e2e_lsm_test.go
  tests/e2e/e2e_setup_test.go
  tests/e2e/e2e_staking_test.go
  tests/e2e/e2e_test.go
  tests/e2e/query.go
  tests/e2e/validator.go
Labels: enhancement, state-machine-breaking, dependencies

#2708 docs: fix typos in release notes template
  RELEASE_NOTES.md
Labels: A:backport/v12.x
