Repository cosmos/gaia, pull requests merged in 2023-02, with the labels that each got.

#2132 chore: Bump ics to rc4
  go.mod
  go.sum
Labels: A:backport/v9.0.x

#2136 docs: Removed Stargazer explorer, now depreciated
  docs/hub-overview/overview.md
Labels: A:backport/v8.0.x, A:backport/v9.0.x

#2137 chore: Update changelog
  CHANGELOG.md
Labels: A:backport/v9.0.x

#2053 Update overview.md
  docs/hub-overview/overview.md
Labels: A:backport/v8.0.x, A:backport/v9.0.x

#2150 chore: bump tm with p2p patch
  go.mod
  go.sum
Labels: A:backport/v8.0.x, A:backport/v9.0.x

#2155 chore: update dependencies for v9
  app/keepers/keepers.go
  go.mod
  go.sum
Labels: A:backport/v9.0.x

#2156 chore: Update changelog for rc3 v9
  CHANGELOG.md
Labels: A:backport/v9.0.x

#2161 Bump forward middleware to v4.0.4
  go.mod
  go.sum
Labels: A:backport/v9.0.x

#2163 chore: bump cosmos-sdk to v0.45.13-ics
  go.mod
  go.sum
Labels: A:backport/v9.0.x

#2164 chore: update CHANGELOG.md
  CHANGELOG.md
Labels: A:backport/v9.0.x

#2146 docs: Updated mlc_config.json to ignore http status responses of 0 and 403
  mlc_config.json
Labels: A:backport/v7.0.x, A:backport/v8.0.x, A:backport/v9.0.x

#2174 chore: bump ics to rc-7
  go.mod
  go.sum
Labels: A:backport/v9.0.x

#2175 chore: update CHANGELOG.md
  CHANGELOG.md
Labels: A:backport/v9.0.x

#2179 Fix missing equivocation prop
  app/modules.go
Labels: A:backport/v9.0.x

#2188 chore: Update required versions outside of replace
  go.mod
  go.sum
Labels: A:backport/v9.0.x

#2170 Updated Joining Testnet Tutorial
  docs/hub-tutorials/join-testnet.md
Labels: A:backport/v9.0.x

#2190 chore: Revert ibc-go to 4.2
  go.mod
  go.sum
Labels: A:backport/v9.0.x

#2197 fix ICS equivocation proposal
  app/keepers/keepers.go
Labels: A:backport/v9.0.x

#2196 docs: First pass with Rho docs
  docs/hub-tutorials/join-mainnet.md
  docs/migration/cosmoshub-4-v8-Rho-upgrade.md
  docs/roadmap/README.md
Labels: A:backport/v8.0.x, A:backport/v9.0.x

#2203 chore: Update migration docs Toc
  docs/migration/cosmoshub-4-v8-Rho-upgrade.md
Labels: A:backport/v8.0.x, A:backport/v9.0.x

#2206 chore: V8 update docs
  docs/getting-started/installation.md
  docs/getting-started/quickstart.md
  docs/guidelines/code-guidelines.md
  docs/hub-tutorials/join-mainnet.md
Labels: A:backport/v8.0.x, A:backport/v9.0.x

#2219 chore: Update changelog for v9 rc7
  CHANGELOG.md
Labels: A:backport/v9.0.x

#2221 chore: Update v8.0.1 changelog
  CHANGELOG.md
Labels: A:backport/v8.0.x, A:backport/v9.0.x

#2018 build: Consistently generate build tags on Make 4.3+
  Makefile
Labels: A:backport/v7.0.x, A:backport/v8.0.x, A:backport/v9.0.x

#2231 chore: Update v9 changelog and mod
  CHANGELOG.md
  go.mod
  go.sum
Labels: A:backport/v9.0.x
