Repository cosmos/gaia, pull requests merged in 2023-04, with the labels that each got.

#2372 fix docker image urls for e2e tests
  Dockerfile
  e2e.Dockerfile
Labels: A:backport/v9.0.x

#2380 docs: Remove Trust Wallet
  docs/hub-overview/overview.md
Labels: A:backport/v8.0.x, A:backport/v9.0.x

#2384 docs: add back trust wallet
  docs/hub-overview/overview.md
Labels: A:backport/v8.0.x, A:backport/v9.0.x

#2377 chore: Fix makefile linting targets
  Makefile
Labels: A:backport/v9.0.x

#2416 fix: remove logger in app.go
  app/app.go
Labels: A:backport/v9.0.x

#2418 update changelog for rc
  CHANGELOG.md
Labels: A:backport/v9.0.x

#2421 update changelog for rc 2
  CHANGELOG.md
Labels: A:backport/v9.0.x

#2185 deps!: bump ibc-go to v4.3.0 and remove dragonberry replace
  go.mod
  go.sum
Labels: state-machine-breaking
