Repository cosmos/gaia, pull requests merged in 2024-05, with the labels that each got.

#3082 tests: create CLI tool to help with mainnet export testing
  cmd/gaiad/cmd/README.md
  cmd/gaiad/cmd/root.go
  cmd/gaiad/cmd/testnet.go
  cmd/gaiad/cmd/testnet_set_local_validator.go
Labels: A:backport/v15.2.x, A:backport/v16.x, A:backport/v17.x

#3099 tests: reduce voting period in testnets exports
  cmd/gaiad/cmd/testnet_set_local_validator.go
Labels: A:backport/v16.x, A:backport/v17.x

#3103 feat!: bump ICS to v4.2.0-lsm
  .changelog/unreleased/dependencies/3103-bump-ics.md
  .changelog/unreleased/features/3103-pss.md
  .changelog/unreleased/state-breaking/3103-pss.md
  go.mod
  go.sum
Labels: A:backport/v17.x

#3106 tests: use top_N in e2e tests
  tests/e2e/e2e_ics_test.go
Labels: A:backport/v17.x

#3113 tests: LastValidatorPower set to voting power value
  cmd/gaiad/cmd/README.md
  cmd/gaiad/cmd/testnet_set_local_validator.go
Labels: A:backport/v17.x
