Repository cosmos/gaia, pull requests merged in 2024-03, with the labels that each got.

#2982 fix!: bump pfm
  .changelog/unreleased/dependencies/2982-bump-pfm.md
  .changelog/unreleased/state-breaking/2982-bump-pfm.md
  go.mod
  go.sum
Labels: A:backport/v15.1.x

#2974 feat/Add snapshot commands
  .changelog/unreleased/features/2974-add-snapshot-commands.md
  cmd/gaiad/cmd/root.go
Labels: A:backport/v15.1.x

#2993 chore!: migrate escrow accounts
  .changelog/unreleased/state-breaking/2993-migrate-escrow-accounts.md
  app/upgrades/v15/upgrades.go
  app/upgrades/v15/upgrades_test.go
Labels: A:backport/v15.1.x

#3009 docs: add v15 specific docs, changelogs and instructions
  docs/docs/changelogs/README.md
  docs/docs/changelogs/_category_.json
  docs/docs/changelogs/v15.1.0.md
  docs/docs/governance/proposal-types/README.md
  docs/docs/governance/proposal-types/_category_.json
  docs/docs/governance/proposal-types/software-upgrade.md
  docs/docs/governance/proposal-types/text-prop.md
  docs/docs/governance/proposals/_category_.json
  docs/docs/governance/submitting.md
  docs/docs/index.mdx
  docs/docs/migration/cosmoshub-4-v15-upgrade.md
Labels: docs, S: KTLO

#3032 fix!: assure historic TxExtensionOptions encoding validity
  x/metaprotocols/types/codec.go
Labels: A:backport/v15.2.x

#3025 fix!: update gov `MaxMetadataLen`
  app/keepers/keepers.go
Labels: type: bug, scope: cosmos-sdk
