Repository cosmos/gaia, pull requests merged in 2024-07, with the labels that each got.

#3193 chore!: bump ICS to v4.3.1-lsm
  .changelog/unreleased/dependencies/3193-bump-ics.md
  .changelog/unreleased/state-breaking/3193-bump-ics.md
  go.mod
  go.sum
Labels: A:backport/v18.1.x

#3211 chore: update CI bots
  .github/dependabot.yml
  .mergify.yml
Labels: scope: CI

#3210 fix: use client/v2 v2.0.0-beta3; fix broken client.toml usage
  cmd/gaiad/cmd/root.go
  go.mod
  go.sum
Labels: scope: CLI, A:backport/v19.x

#3227 deps: use ibc-apps rate limiter import
  .changelog/unreleased/dependencies/3227-bump-ibc-rate-limits.md
  ante/gov_vote_ante.go
  app/keepers/keepers.go
  app/keepers/keys.go
  app/modules.go
  cmd/gaiad/cmd/testnet_set_local_validator.go
  go.mod
  go.sum
  tests/e2e/chain.go
  tests/e2e/query.go
Labels: A:backport/v19.x

#3230 deps!: use fixed cosmwasm version (v0.51.0)
  .github/workflows/test.yml
  Dockerfile
  Makefile
  app/helpers/test_helpers.go
  app/keepers/keepers.go
  app/sim_test.go
  go.mod
  go.sum
  tests/integration/ibcfee_test.go
  tests/integration/interchain_security_test.go
  tests/integration/test_utils.go
Labels: state-machine-breaking, dependencies, A:backport/v19.x

#3205 ci: First run at interchaintests.
  .github/workflows/docker-push.yml
  .github/workflows/interchain-test.yml
  .github/workflows/test.yml
  Dockerfile
  tests/interchain/README.md
  tests/interchain/chainsuite/chain.go
  tests/interchain/chainsuite/chain_ics.go
  tests/interchain/chainsuite/config.go
  tests/interchain/chainsuite/context.go
  tests/interchain/chainsuite/envconfig.go
  tests/interchain/chainsuite/http.go
  tests/interchain/chainsuite/relayer.go
  tests/interchain/chainsuite/suite.go
  tests/interchain/configuredChains.yaml
  tests/interchain/consumer_launch_test.go
  tests/interchain/go.mod
  tests/interchain/go.sum
  tests/interchain/matrix_tool/main.go
  tests/interchain/txs_test.go
Labels: scope: testing

#3237 deps!: use fixed ics v5.1.1.
  go.mod
  go.sum
Labels: dependencies, A:backport/v19.x

#3239 ci: update goreleaser to v2
  .goreleaser.yml
  Makefile
Labels: scope: CI, A:backport/v19.x

#3247 ci: Add an interchain test for unbond-validator.
  tests/interchain/txs_test.go
Labels: scope: CI, A:backport/v19.x
