Repository cosmos/gaia, pull requests merged in 2024-08, with the labels that each got.

#3249 deps!: use fixed cosmos-sdk/lsm
  contrib/single-node.sh
  go.mod
  go.sum
Labels: scope: cosmos-sdk, A:backport/v19.x

#3253 fix!: avoid state break in wasm
  app/keepers/keepers.go
Labels: A:backport/v19.x

#3270 fix(cometbft) Prevent panic on non-nil proposal without vote extensions
  .changelog/unreleased/dependencies/3270-bump-cometbft.md
  go.mod
  go.sum
Labels: A:backport/v19.1.x
